name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build (no default features)
      run: cargo build --no-default-features --verbose
    - name: Test (no default features)
      run: cargo test --no-default-features --verbose
    - name: Build (fallible + serde)
      run: cargo build --features fallible,serde --verbose
    - name: Test (fallible + serde)
      run: cargo test --features fallible,serde --verbose

  build-nightly:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install nightly
      uses: dtolnay/rust-toolchain@nightly
    - name: Build (const-realfft, nightly)
      run: cargo build --all-features --verbose
    - name: Test (const-realfft, nightly)
      run: cargo test --all-features --verbose
